pipelines:
  - name: eda
    type: pipelines.eda_pipeline.EDAPipeline
    enabled: true
    params:
      save_path: output/eda/boards
      steps:
#            - name: group_count_distribution
#              params:
#                value_column: commentID
#                group_by_columns: [discussionID, categoryID]
#                summary_group_columns:
#                  - categoryID
#
#                viz_params:
#                  - name: histogram
#                    filename: boards_comments_per_discussion_per_forum_histogram.png
#                    #title: Distribution of Comments per Discussion
#                    xlabel: Number of Comments per Discussion
#                    ylabel: Number of Discussions
#                    bins: 30
#                    xscale: log
#
#                  - name: boxplot
#                    filename: boards_comments_per_discussion_per_forum_boxplot.png
#                    x_column: categoryID
#                    y_column: Count
#                    yscale: log
#                    ylabel: Number of Comments per Discussion (log scale)
#            - name: group_count_distribution
#              params:
#                value_column: commentID
#                group_by_columns: [discussionID]
#
#                viz_params:
#                  - name: histogram
#                    filename: boards_comments_per_discussion_histogram.png
#                    #title: Distribution of Comments per Discussion
#                    xlabel: Number of Comments per Discussion
#                    ylabel: Number of Discussions
#                    bins: 30
#                    xscale: log
#
#                  - name: boxplot
#                    filename: boards_comments_per_discussion_boxplot.png
#                    yscale: log
#                    ylabel: Number of Comments per Discussion (log scale)
#            - name: class_balance
#              params:
#                #target: null  # When target is null, ClassBalanceEDA will create subplots for all columns
#                exclude_columns:
#                  - ID
#                  - commentID
#                  - discussionID
#                  - parentRecordType
#                  - parentRecordID
#                  - name
#                  - body
#                  - dateInserted
#                  - dateUpdated
#                  - updateUserID
#                  - score
#                  - depth
#                  - scoreChildComments
#                  - countChildComments
#                  - url
#                  - type
#                  - format
#      #          log_transform_columns:
#      #            - numeric_score
#                # Can be an int (global bins) or a dict mapping column->bins
#                #hist_bins: 30
#                filename: boards_category_class_balance.png
#                #save_path: output/eda

            - name: temporal_analysis
              params:
                date_field: dateInserted
                aggregate_by: month
#                saver_name: sql_server
#                table_name: boards_temporal_analysis
#                if_exists: replace
#                schema: dbo
                viz_params:
                  - name: line_plot
                    #title: Temporal Analysis of Questions Over Time
                    xlabel: Date
                    ylabel: Number of Comments
                    filename: boards_temporal_comments_line_plot.png
                    include_mean: true
                    mean_line_colour: red
                    x_axis_frequency: monthly
                  - name: area_plot
                    #title: Temporal Analysis of Questions Over Time
                    xlabel: Date
                    ylabel: Number of Comments
                    filename: boards_temporal_comments_area_plot.png
                    include_mean: true
                    mean_line_colour: red
                    area_alpha: 0.5
                    x_axis_frequency: monthly

