# file: `config/pipelines_boards/0500000_boards_bertopic_experiments.yaml
name: topic_modeling_bertopic
type: pipelines.topic_modeling_pipeline.TopicModelingPipeline
enabled: true
params:
  model_name: bertopic
  dataset_name: online_forum
  evaluator_name: topic_modeling
  evaluator_params:
    top_n_topics: 100
  mlflow_experiment: baseline
  representation_text_field: RepresentationDocument
  experiment_refs:
    - config/experiments/boards/minilm_embeddings_baseline.yaml
    - config/experiments/boards/roberta_embeddings_baseline.yaml
    - config/experiments/boards/rooseberta_embeddings_baseline.yaml

#   - config/experiments/minilm_embeddings.yaml
#    - config/experiments/roberta_embeddings.yaml
#    - config/experiments/rooseberta_embeddings.yaml
#    - config/experiments/mpnet_embeddings.yaml
#    - config/experiments//minilm_embeddings_baseline.yaml