## file: `config/pipelines_boards/0500000_boards_bertopic_experiments.yaml
#name: topic_modeling_bertopic
#type: pipelines.topic_modeling_pipeline.TopicModelingPipeline
#enabled: true
#params:
#  model_name: bertopic
#  dataset_name: online_forum
#  evaluator_name: topic_modeling
#  evaluator_params:
#    top_n: 10
#  mlflow_experiment: online_forum_optimised_experiments
#  representation_text_field: RepresentationDocument
#  experiment_refs:
#
#
#     # MiniLM Sweeps
#    - config/experiments/boards/minilm/05500_minilm_embeddings_baseline.yaml
#    - config/experiments/boards/minilm/06000_minilm_final_optimisation.yaml
##    - config/experiments/boards/minilm/01000_minilm_reducer.yaml
##    - config/experiments/boards/minilm/02000_minilm_clusterer.yaml
##    - config/experiments/boards/minilm/03000_minilm_vectorizer.yaml
##    - config/experiments/boards/minilm/04000_minilm_ctfidf.yaml
##    - config/experiments/boards/minilm/05000_minilm_representation.yaml
#
#     # RoBERTa Sweeps
#    - config/experiments/boards/roberta/05500_roberta_embeddings_baseline.yaml
#    - config/experiments/boards/roberta/06000_roberta_final_optimisation.yaml
##    - config/experiments/boards/roberta/01000_roberta_reducer.yaml
##    - config/experiments/boards/roberta/02000_roberta_clusterer.yaml
##    - config/experiments/boards/roberta/03000_roberta_vectorizer.yaml
##    - config/experiments/boards/roberta/04000_roberta_ctfidf.yaml
##    - config/experiments/boards/roberta/05000_roberta_representation.yaml
#
#    # RooseBERT Sweeps
#    - config/experiments/boards/roosebert/05500_roosebert_embeddings_baseline.yaml
#    - config/experiments/boards/roosebert/06000_roosebert_final_optimisation.yaml
##    - config/experiments/boards/roosebert/01000_roosebert_reducer.yaml
##    - config/experiments/boards/roosebert/02000_roosebert_clusterer.yaml
##    - config/experiments/boards/roosebert/03000_roosebert_vectorizer.yaml
##    - config/experiments/boards/roosebert/04000_roosebert_ctfidf.yaml
##    - config/experiments/boards/roosebert/05000_roosebert_representation.yaml
