#pipelines:
#- name: preprocess_boards_data
#  type: pipelines.preprocessing_pipeline.PreprocessingPipeline
#  enabled: false
#  params:
#    preprocessors:
#      - name: combine_text
#        params:
#          fields_to_combine: [ "QuestionText", "AnswerText" ]
#          combined_field_name: "CombinedOireachtasText"

