# file: `config/pipelines/topic_modeling_bertopic.yaml`
name: topic_modeling_bertopic
type: pipelines.topic_modeling_pipeline.TopicModelingPipeline
enabled: true
params:
  model_name: bertopic
  dataset_name: parliamentary_questions
  evaluator_name: topic_modeling
  evaluator_params:
    top_n_topics: 100
  mlflow_experiment: baseline
  representation_text_field: RepresentationDocument
  experiment_refs:
    - config/experiments/minilm_embeddings_baseline.yaml
    - config/experiments/roberta_embeddings_baseline.yaml
    - config/experiments/rooseberta_embeddings_baseline.yaml

    - config/experiments/01000_minilm_reducer.yaml
    - config/experiments/02000_minilm_clusterer.yaml
    - config/experiments/03000_minilm_vectorizer.yaml
    - config/experiments/04000_minilm_ctfidf.yaml
    - config/experiments/05000_minilm_representation.yaml

#   - config/experiments/minilm_embeddings.yaml
#    - config/experiments/roberta_embeddings.yaml
#    - config/experiments/rooseberta_embeddings.yaml
#    - config/experiments/mpnet_embeddings.yaml
#    - config/experiments//minilm_embeddings_baseline.yaml